/**
 * Traces Pi Extension
 *
 * Provides deep integration between Traces and Pi:
 *
 * 1. Registers a `traces_share` tool that the LLM can call directly.
 * 2. Registers a `traces_list` tool for discovering available traces.
 * 3. Forwards Pi lifecycle events to `traces hook agent`.
 *
 * Install:
 *   Copy this file to ~/.pi/agent/extensions/traces.ts
 *   Or to .pi/extensions/traces.ts for project-local install.
 */
// Auto-generated by traces
// Do not edit manually -- changes will be overwritten on next install.
import { spawn } from "node:child_process";
import { StringEnum, Type } from "@mariozechner/pi-ai";
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

type ShareVisibility = "public" | "direct" | "private";

type TracesCommandResult = {
  stdout: string;
  stderr: string;
  exitCode: number | null;
};

function runTraces(
  args: string[],
  options: {
    cwd?: string;
    env?: Record<string, string>;
    stdin?: string;
  } = {},
): Promise<TracesCommandResult> {
  return new Promise((resolve, reject) => {
    const proc = spawn("traces", args, {
      cwd: options.cwd,
      env: {
        ...process.env,
        ...options.env,
      },
      stdio: ["pipe", "pipe", "pipe"],
      timeout: 30000,
    });

    let stdout = "";
    let stderr = "";

    proc.stdout.on("data", (chunk) => {
      stdout += chunk.toString();
    });

    proc.stderr.on("data", (chunk) => {
      stderr += chunk.toString();
    });

    proc.on("error", reject);
    proc.on("close", (exitCode) => {
      resolve({ stdout, stderr, exitCode });
    });

    proc.stdin.end(options.stdin ?? "");
  });
}

function tryParseJson(text: string): any | null {
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

function textResult(text: string, details: Record<string, unknown> = {}) {
  return {
    content: [{ type: "text", text }],
    details,
  };
}

export default function tracesExtension(pi: ExtensionAPI): void {
  const inheritedTraceId = process.env.TRACES_CURRENT_TRACE_ID;
  const inheritedAgent = process.env.TRACES_CURRENT_AGENT;

  function exposeSessionIdentity(sessionId: string): void {
    // Pi's session id is the trace id, so every tool subprocess can identify
    // the exact session without guessing from recency.
    process.env.TRACES_CURRENT_TRACE_ID = sessionId;
    process.env.TRACES_CURRENT_AGENT = "pi";
  }

  function restoreInheritedIdentity(): void {
    if (inheritedTraceId === undefined) delete process.env.TRACES_CURRENT_TRACE_ID;
    else process.env.TRACES_CURRENT_TRACE_ID = inheritedTraceId;
    if (inheritedAgent === undefined) delete process.env.TRACES_CURRENT_AGENT;
    else process.env.TRACES_CURRENT_AGENT = inheritedAgent;
  }

  function callHook(event: string, payload: Record<string, unknown>): void {
    const stdin = JSON.stringify(payload) + "\n";
    void runTraces(["hook", "agent", event, "--agent", "pi"], {
      cwd: process.cwd(),
      stdin,
    }).catch(() => {
      // Ignore hook delivery errors to avoid blocking Pi.
    });
  }

  function getSessionId(ctx: any): string | null {
    const sid = ctx?.sessionManager?.getSessionId?.();
    return typeof sid === "string" && sid.length > 0 ? sid : null;
  }

  let currentSessionId: string | null = null;

  pi.on("session_start", (_event: any, ctx: any) => {
    const sid = getSessionId(ctx);
    if (!sid) return;
    currentSessionId = sid;
    exposeSessionIdentity(sid);
    callHook("session-start", { session_id: sid });
  });

  pi.on("agent_start", (_event: any, ctx: any) => {
    const sid = getSessionId(ctx) ?? currentSessionId;
    if (!sid) return;
    currentSessionId = sid;
    callHook("prompt-submitted", { session_id: sid });
  });

  function reportAgentDone(ctx: any): void {
    const sid = getSessionId(ctx) ?? currentSessionId;
    if (!sid) return;
    currentSessionId = sid;
    callHook("agent-done", { session_id: sid });
  }

  // Prefer agent_settled: Pi emits agent_end once per attempt from inside its
  // retry/compaction loop, but agent_settled once per prompt from that loop's
  // finally block. Extensions cannot tell a retry from a real ending -- Pi
  // computes `willRetry` but strips it from the event it hands to extensions.
  //
  // agent_settled only exists from Pi 0.80.5, and Pi's loader accepts a
  // subscription to an unknown event without firing it, so agent_end stays
  // registered as the fallback for older Pi. Once a settled event arrives we
  // know this Pi has it, and agent_end stands down for the rest of the session.
  // Session-scoped by design: this extension is instantiated per Pi session, so
  // the flag must stay inside it rather than being hoisted to module scope.
  let sawAgentSettled = false;

  pi.on("agent_settled", (_event: any, ctx: any) => {
    sawAgentSettled = true;
    reportAgentDone(ctx);
  });

  pi.on("agent_end", (_event: any, ctx: any) => {
    if (sawAgentSettled) return;
    reportAgentDone(ctx);
  });

  pi.on("session_shutdown", (_event: any, ctx: any) => {
    const sid = getSessionId(ctx) ?? currentSessionId;
    if (sid) callHook("session-end", { session_id: sid });
    currentSessionId = null;
    restoreInheritedIdentity();
  });

  pi.registerTool({
    name: "traces_share",
    label: "Share to Traces",
    description:
      "Share the current coding session to Traces and return the share URL. " +
      "Use when the user asks to share, publish, or export their session.",
    parameters: Type.Object({
      visibility: Type.Optional(
        StringEnum(["public", "direct", "private"] as const, {
          description:
            "Only set if the user explicitly requests a visibility level (e.g. 'share as public'). Omit to use the correct default based on namespace type.",
        }),
      ),
    }),
    async execute(_toolCallId, params, signal) {
      if (signal?.aborted) {
        return textResult("Share cancelled.");
      }

      const input = (params ?? {}) as { visibility?: ShareVisibility };
      const args = ["share", "--cwd", process.cwd(), "--agent", "pi", "--json"];
      if (input.visibility) {
        args.push("--visibility", input.visibility);
      }

      try {
        const env: Record<string, string> = {
          TRACES_CURRENT_AGENT: "pi",
        };
        if (currentSessionId) {
          env.TRACES_CURRENT_TRACE_ID = currentSessionId;
        }

        const result = await runTraces(args, {
          cwd: process.cwd(),
          env,
        });

        const parsed = tryParseJson(result.stdout);
        if (result.exitCode === 0 && parsed?.ok) {
          return textResult(
            `Session shared!\nURL: ${parsed.data.sharedUrl}\nTrace: ${parsed.data.traceId} (${parsed.data.agentId})\nSelected by: ${parsed.data.selectedBy}`,
            { response: parsed.data },
          );
        }

        const errorPayload = tryParseJson(result.stderr) ?? parsed;
        if (errorPayload?.error) {
          return textResult(
            `Share failed (${errorPayload.error.code}): ${errorPayload.error.message}`,
            { response: errorPayload.error },
          );
        }

        return textResult(`Share failed: ${(result.stderr || result.stdout).trim() || "Unknown error"}`);
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        return textResult(
          `Failed to share: ${message}. Ensure 'traces' CLI is installed and you are logged in.`,
        );
      }
    },
  });

  pi.registerTool({
    name: "traces_list",
    label: "List Traces",
    description:
      "List available traces that can be shared. " +
      "Use to discover sessions before sharing.",
    parameters: Type.Object({
      agent: Type.Optional(
        Type.String({
          description: "Filter by agent ID. Omit to show all.",
        }),
      ),
    }),
    async execute(_toolCallId, params, signal) {
      if (signal?.aborted) {
        return textResult("Trace listing cancelled.");
      }

      const input = (params ?? {}) as { agent?: string };
      const args = ["share", "--list", "--cwd", process.cwd(), "--json"];
      if (input.agent) {
        args.push("--agent", input.agent);
      }

      try {
        const result = await runTraces(args, { cwd: process.cwd() });
        const parsed = tryParseJson(result.stdout);

        if (result.exitCode === 0 && parsed?.ok && parsed.data.traces.length > 0) {
          const lines = parsed.data.traces.map(
            (trace: {
              id: string;
              agentId: string;
              title: string;
              timestamp: number;
              sharedUrl?: string;
            }) => {
              const timestamp = new Date(trace.timestamp).toISOString();
              const shared = trace.sharedUrl ? ` [shared: ${trace.sharedUrl}]` : "";
              return `${timestamp}  ${trace.agentId}  ${trace.id}  ${trace.title}${shared}`;
            },
          );

          return textResult(`Found ${parsed.data.count} trace(s):\n${lines.join("\n")}`, {
            response: parsed.data,
          });
        }

        if (result.exitCode === 0 && parsed?.ok) {
          return textResult("No traces found.", { response: parsed.data });
        }

        const errorPayload = tryParseJson(result.stderr) ?? parsed;
        if (errorPayload?.error) {
          return textResult(
            `Failed to list traces (${errorPayload.error.code}): ${errorPayload.error.message}`,
            { response: errorPayload.error },
          );
        }

        return textResult(
          `Failed to list traces: ${(result.stderr || result.stdout).trim() || "Unknown error"}`,
        );
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        return textResult(`Failed to list traces: ${message}`);
      }
    },
  });
}
